import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { HotelProvider } from "./context/HotelContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "RST Tool",
  description: "Generated by create next app",
  icons: {
    icon: "/hotel.png",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HotelProvider>
        {children}
        </HotelProvider>
      </body>
    </html>
  );
}
